apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi-v1
  namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapi
      version: v1
  template:
    metadata:
      labels:
        app: myapi
        version: v1
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo
        imagePullPolicy: IfNotPresent
        args:
        - "-text=myapi v1"
        ports:
        - containerPort: 5678